/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;


public class App {
    public static void main(String[] args) {
        String losango;
        String triangulo;
        String retangulo;

        // caso ele responda algo inválido
        do {
            System.out.print("Entre com a forma: ");
            String forma = args[0];
            int num = args[1];
        } while (num < 0);

        for ()
//        System.out.print("Entre com uma forma: ");
//        int forma = teclado.nextInt();


    }
}
