/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Random;

public class App {
    public static void main(String[] args) {

        char frota[][] = new char[10][10];
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                frota[i][j] = '.';
            }
        }

        char[] navios = {'P', 'E', 'C', 'S', 'N'};
        int[] tamanhosN = {5, 4, 3, 3, 2};

        for (int i = 0; i < navios.length; i++) {
            frota = colocarNavio(tamanhosN[i], frota, navios[i]);
        }

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                System.out.print(frota[i][j] + " ");
            }
            System.out.println();
        }
    }

    public static char[][] colocarNavio (int tamanhoN, char[][] frota, char navios) {
        // sortear primeira posição (dois numeros sorteados = valor de I e valor de J)
        // Verificar se a posicao + o tamanhoN, se ela é menor do que 10.
        // verificar se a tem um ponto no lugar (i e j != ".")
        // Criar um for para não haver empate de navio.
        // Para cada ponto eu troco para letra do navio, da posicao inicial (i) + o tamanhoN
        // se não for válido, ele tenta sortear de novo (até conseguir).

        int x = 0;
        int y = 0;
        boolean excedeTamanho = false;
        boolean sobrescreveNavio = false;

        // posicao válida
        do {
            excedeTamanho = false;
            sobrescreveNavio = false;

            Random sorteador = new Random();
            x = sorteador.nextInt(0, 10);
            y = sorteador.nextInt(0, 10);

            if (tamanhoN + x > 10) {
                excedeTamanho = true;
            } else {
                for (int i = x; i < x + tamanhoN; i++) {
                    if (frota[i][y] != '.') {
                        sobrescreveNavio = true;
                        break;
                    }
                }
            }
        } while (sobrescreveNavio || excedeTamanho);
        

    }
}
