/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;


public class App {
    public static void main(String[] args) {

        // verificar se foi escrito certo a string.
        String erro = "Forma de uso incorreta.\nForma correta:\nPara triangulos e losangulos -> 'gradle run --args '{forma} {tamanho}'\nPara quadrados -> 'gradle run --args '{forma} {altura} {largura}'";

        // erros que podem acontecer.
        try {
            String forma = args[0];
            int tamanho = Integer.parseInt(args[1]);
            if (tamanho < 1) {
                System.out.println("Errado. Tente novamente.");
            }
            switch (forma.toLowerCase()) {
                case "triangulo":
                    fazerTriangulo(tamanho);
                    break;
                case "losangulo":
                    fazerLosangulo(tamanho);
                    break;
                case "quadrado":
                    int largura = Integer.parseInt(args[2]);
                    fazerRetangulo(tamanho, largura);
                    break;
                default:
                    System.out.println(erro);
                    break;
            }
        } catch (Exception ex) {
            System.out.println(erro);
        }
    }

    public static void fazerTriangulo(int tamanho) {
        for (int i = 1; i <= tamanho; i++) {
            System.out.println();
            for (int j = 1; j <= i; j++) {
                System.out.print("* ");
            }
        }
    }

    public static void fazerLosangulo(int tamanho) {
        int asteristicos = 1;
        int espaco = tamanho - 1;
        if (tamanho % 2 == 0 || tamanho < 1) {
            System.out.println("\nPor favor, para formação de losangulos, infome um tamanho ímpar");
        } else {
            for (int j = 1; espaco / 2 > 0; j++) {
                for (int i = 1; i <= espaco / 2; i++) {
                    System.out.print(" ");
                }
                for (int i = 1; i <= asteristicos; i++) {
                    System.out.print("*");
                }
                espaco = espaco - 2;
                asteristicos = asteristicos + 2;
                System.out.println();
            }
            for (int j = 1; asteristicos > 0; j++) {
                for (int i = 1; i <= espaco / 2; i++) {
                    System.out.print(" ");
                }
                for (int i = 1; i <= asteristicos; i++) {
                    System.out.print("*");
                }
                espaco = espaco + 2;
                asteristicos = asteristicos - 2;
                System.out.println();
            }
        }
    }

    public static void fazerRetangulo(int altura, int largura) {
    for (int i = 1; i <= largura; i++) {
        System.out.print("*");
    }
    System.out.println();
    for (int i = 1; i <= altura - 2; i++) {
        System.out.print("*");
        for (int j = 1; j <= largura - 2; j++) {
            System.out.print(" ");
        }
        System.out.print("*");

        System.out.println();
    }
    for (int i = 1; i <= largura; i++) {
        System.out.print("*");
    }
}
}