/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        // fazer tres switch para as faixas
        // eu preciso verificar 
    }
}
